-- Adjust identity to allow explicit sequence override (for "call now" front insertion).
-- Safe if already BY DEFAULT.
DO $$
BEGIN
    IF EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_schema = 'public' AND table_name = 'calls' AND column_name = 'sequence'
    ) THEN
        ALTER TABLE public.calls ALTER COLUMN sequence DROP IDENTITY IF EXISTS;
        ALTER TABLE public.calls ALTER COLUMN sequence ADD GENERATED BY DEFAULT AS IDENTITY;
    END IF;
END $$;
